name: Capable Fly
main: capablefly.Principal
version: 1.2.05
commands:
 cfly:
  description: Te permite volar por un tiempo determinado
  usage: /cfly (activar/desactivar) , /cfly help (para saber cuanto tiempo queda)